### ISSUE TITLE
The blog post, it is gone

### ISSUE THREAD

**Issue by Jens0512** [jfo/zigf#1]
In you README, you say "See https://blog.jfo.click/how-zig-do/" ─ but there is naught (but 404) there.

Dear Jeff, I really loved that blog post ─ "How zig do," ─ enough to come back to search for it a couple of times, but I could not find it, and I've come no further. Seriously, it was a great post. I loved it, and now I miss it.

Please, I beg of you, can you publish it once again?

Cheers

**Comment by jfo** [comment]
Hello @Jens0512, I am sorry I never responded to this. 

The link is alive again and has been for quite a while, there was a week window when my pro github account expired and I had forgotten to move the blog to a public repo (private repos don't host public gh-pages on non-pro accounts)

I am glad you like it and hope you found it again anyway!

**Comment by Jens0512** [comment]
Hooray!

> there was a week window

Ah, my luck. Anyways, thanks so much for this.
